version: '3.8'
services:
  mongodb:
    image: mongo:latest
    command: [--auth]
    container_name: stockdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: addressAdmin
      MONGO_INITDB_ROOT_PASSWORD: addressPassword
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/address/db

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_HOST: root
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: addressdb
    depends_on:
      - mongodb
    ports:
      - 8080:8080

volumes:
  mongo-data: